-- ============================================================================
-- call-tracker: ゲスト（販売店）アカウントによる自動ツール・AIエージェントを使った
-- 大量データ取得を抑止するための、簡易レート制限（アクセス頻度制限）
--
-- 背景：
--   コールトラッカーの全ページはログイン必須で、データベース側もRow Level
--   Security（行単位のアクセス制御）で守られているため、外部から未ログインで
--   データを抜き取ることはできない。
--   一方で、すでに正規にログインできる販売店（ゲスト）アカウントが、人力の代わりに
--   ブラウザ自動操作やAIエージェントなどを使って、リード一覧・詳細ページを
--   短時間に機械的に大量アクセスし、本来の利用範囲を超えて一括でデータを
--   抜き出すことは、技術的には可能だった。これを防ぐため、2026-10-02、
--   ヒロさんのご依頼で導入。
--
--   仕組み：ゲストロール（guest_admin・guest_member）がリード一覧・リード詳細の
--   各ページを開くたびに、直近一定時間（ウィンドウ）内の本人のアクセス回数を記録・
--   カウントし、しきい値を超えていたらデータを返さず「アクセスが集中しています」
--   という案内だけを表示する（アプリ側 app/(app)/leads/page.tsx,
--   app/(app)/leads/[id]/page.tsx, lib/rateLimit.ts を参照）。
--   管理者・チームリーダー・スタッフ（社内メンバー）の通常業務には影響しないよう、
--   このチェックはゲストロールにのみ適用している。
--
--   さらに、しきい値を超えて実際にブロックされたアクセスは blocked = true として
--   記録し、メンバー管理画面（/members）の上部に「アクセス集中の検知」として
--   一覧表示する（app/(app)/members/page.tsx, MembersClient.tsx を参照）。
--   これにより、実際に自動ツールなどで大量アクセスが試みられた場合に、
--   管理者が画面を見るだけで気づけるようにしている。
-- ============================================================================

create table public.access_log (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  route text not null,
  blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create index access_log_profile_route_created_idx
  on public.access_log(profile_id, route, created_at desc);

alter table public.access_log enable row level security;

-- 書き込みは check_rate_limit() 関数（security definer）経由でのみ行う前提だが、
-- 念のため本人分のみ挿入可能にしておく。
create policy access_log_insert on public.access_log for insert
  with check (profile_id = (select auth.uid()));

-- アクセス状況の確認用に、管理者・オーナーのみ閲覧可能にしておく。
create policy access_log_select on public.access_log for select
  using (
    (select public.current_role()) = 'admin' or (select public.current_is_owner())
  );

-- レート制限の判定・記録を1回でまとめて行う関数。
-- 呼び出しごとに1件アクセス記録を残し、直近 p_window_seconds 秒以内の
-- 本人・同一route宛てのアクセス件数が p_max_requests 件を超えていなければ true
-- （問題なし）、超えていれば false（アクセス集中として拒否）を返す。
-- しきい値を超えた場合は、今回の記録に blocked = true を立てる
-- （メンバー管理画面でのアラート表示に使う）。
create or replace function public.check_rate_limit(p_route text, p_window_seconds int, p_max_requests int)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_count int;
  v_id bigint;
  v_exceeded boolean;
begin
  if v_uid is null then
    return true;
  end if;

  insert into public.access_log (profile_id, route) values (v_uid, p_route)
  returning id into v_id;

  select count(*) into v_count
  from public.access_log
  where profile_id = v_uid
    and route = p_route
    and created_at > now() - make_interval(secs => p_window_seconds);

  v_exceeded := v_count > p_max_requests;

  if v_exceeded then
    update public.access_log set blocked = true where id = v_id;
  end if;

  return not v_exceeded;
end;
$$;

-- access_log は呼ばれるたびに増え続けるため、古い記録を消すための掃除関数。
-- ただし blocked = true（アクセス集中として検知した記録＝アラート）は、
-- メンバー管理画面で後から気づけるように、通常の記録より長く残すため、
-- 既定では消さない（p_include_blocked を true にした場合のみ、
-- p_older_than_hours より古いアラートもまとめて消せる＝確認済みの意味で使う）。
-- 今のところ自動実行はされないので、データ量が気になってきたら、
-- SupabaseのSQL Editorから select public.cleanup_access_log(); を手動実行すれば良い。
create or replace function public.cleanup_access_log(p_older_than_hours int default 24, p_include_blocked boolean default false)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.access_log
  where created_at < now() - make_interval(hours => p_older_than_hours)
    and (p_include_blocked or not blocked);
$$;
